In [6]:
import numpy as np 

# numpy 라는 이름이 너무 길어서 np라고 부를거야
my_list = list(range(1000000))
my_array = np.arange(1000000)


In [7]:
%timeit my_list2 = [i * 2 for i in my_list]
%timeit my_array2 = my_array * 2

54.2 ms ± 2.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.3 ms ± 232 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
a = [
    [1, 1.2, 3],
    [-123, 123, 0]
]

data = np.array(a)
print(data) # 뒤에 . 을 붙여서 데이터의 형태를 맞춰줌

[[   1.     1.2    3. ]
 [-123.   123.     0. ]]


In [12]:
# 0차원 : 스칼라(scala)
# 1차원 : 벡터(vector)
# 2차원 : 행렬(matrix), 
# 3차원 : 텐서(tenser)
print(data * 10)
print(data + data)

[[   10.    12.    30.]
 [-1230.  1230.     0.]]
[[   2.     2.4    6. ]
 [-246.   246.     0. ]]


In [16]:
print(data.shape) # 가장 바깥에 있는 배열이 2개, 안쪽에 3개 
print(data.dtype) # 안쪽의 데이터 타입 

(2, 3)
float64


## ndarray 생성하기

In [19]:
## list = array(좀 더 고정된 느낌)

In [23]:
data1 = [1, 2, 3, 4, 5]
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [29]:
arr2 = np.array( [[1.1, 2.2], [3.3 , 4.4]])
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [30]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [31]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 2)


In [68]:
print(np.zeros(10))
print([0] * 10)
print(np.zeros(  (5, 5)  )) # (n, n)형태로 만들기
print(np.empty((2, 2, 2))) # 비어있는 리스트를 만들었음 그래서 숫자는 무작위로 들어감 


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[4.67296746e-307 1.69121096e-306]
  [1.60219035e-306 1.89146896e-307]]

 [[7.56571288e-307 3.11525958e-307]
  [1.24610723e-306 1.29061142e-306]]]


In [40]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


# ndarray 자료형

In [45]:
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)

print(arr2.dtype)

float64
int32


In [50]:
arr1 = np.array([1, 2, 3])
print(arr1.dtype)
float_arr1 = arr1.astype(np.float64) # 형변환을 시키는 함수
print(float_arr1)
print(float_arr1.dtype)

int64
[1. 2. 3.]
float64


In [53]:
arr2 = np.array([1.1, 2.2, 3.3])
print(arr2.dtype)
int_arr2 = arr2.astype(np.int64) # int로 형변환을 해서 뒤에 소수점이 날라감
print(int_arr2)
print(int_arr2.dtype)

float64
[1 2 3]
int64


## 산술 연산

In [58]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [63]:
print(arr * arr)
print(arr + arr)
print(1 / arr)
print(arr ** 3)
# 사칙연산은 같은 위치에 있는 애들끼리가 기본값

[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [67]:
arr2 = np.array([[3, 2, 1], [1, 2, 3]])
print(arr)
print(arr, arr2)
print(arr > arr2)
print(arr == 3)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]] [[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[False False  True]
 [False False False]]


## 색인(인덱싱)과 슬라이싱

In [71]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [76]:
arr[7]
print(arr[7])
print(arr[2:5])

7
[2 3 4]


In [82]:
arr[2:5] = 10
print(arr) # 파이썬은 슬라이싱을 해도 원본이 유지됐지만 arr은 원본도 바뀜

[ 0  1 10 10 10  5  6  7  8  9]


In [81]:
py_list = [1, 2, 3, 4, 5]
py_list[2:3].pop() # 원본은 그대로 있음
print(py_list)

[1, 2, 3, 4, 5]


In [85]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [89]:
print(arr[0]) # 0번째 데이터는 [1, 2, 3] 1번쨰 데이터는 [4, 5, 6]
print(arr[1][1])
print(arr [1, 1])

[1 2 3]
5
5


In [93]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
          [[11, 12, 13], [14, 15, 16], [17, 18, 19]], 
          [[11, 22, 33], [44, 55, 66], [77, 88, 99]]])

In [98]:
print(arr3d[2][0][1])
print(arr3d [2, 0, 1])

22
22


In [100]:
print(arr3d[:1]) # 0번째 데이터만 출력
print(arr3d[:1, 1:, 2:])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[6]
  [9]]]


In [101]:
arr3d[0, 1:, 2:]

array([[6],
       [9]])

In [103]:
arr3d[0, 1:, 2:] = 9999
print(arr3d)

[[[   1    2    3]
  [   4    5 9999]
  [   7    8 9999]]

 [[  11   12   13]
  [  14   15   16]
  [  17   18   19]]

 [[  11   22   33]
  [  44   55   66]
  [  77   88   99]]]


## 불리언 값으로 선택

In [104]:
names = np.array(['hong', 'kim', 'hong', 'kim'])
data = np.array([['math', 60], ['math', 90], ['eng', 70], ['eng', 50]])

In [107]:
# hong의 데이터만 추출하고 싶을때
names == 'hong'

array([ True, False,  True, False])

In [111]:
# data[[True, False, True, False]]에서 True만 출력한것
data[names == 'hong'] # 특정 조건에 맞는 데이터를 고를 때

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [179]:
data[names == 'hong', 1] # 인덱스 접근
print(data[names == 'hong', :1]) # 슬라이싱 접근

[['math']
 ['eng']]


In [181]:
names = np.array(['do', 'deft', 'hanhwa', 'yerin'])

In [184]:
names == 'yerin'

array([False, False, False,  True])

In [187]:
data = np.array(['exo', 'lol', 'baseball', 'min'])

In [189]:
data[names == 'yerin']

array(['min'], dtype='<U8')

In [192]:
data[names == 'yerin', 1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [116]:
print(names != 'hong')

[False  True False  True]


In [118]:
print(~(names == 'hong')) # ~는 계산을 먼저 한 후 역을 보여주는것

[False  True False  True]


In [119]:
cond = names == 'kim'
data[cond]

array([['math', '90'],
       ['eng', '50']], dtype='<U21')

## 팬시 색인(fancy indexing)

In [126]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [129]:
arr[[4, 3, 0, 5]] # []안에 [] > [[]] 4번째 3번째 0번째 5번째 내가 원하는 특정 데이터에 접근할때

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [130]:
arr[[-3, -5, -1]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [133]:
print(arr[[1, 5]])
print(arr[[1, 5], [0, 2]])

[[1. 1. 1. 1.]
 [5. 5. 5. 5.]]
[1. 5.]


In [140]:
arr = np.arange(32).reshape(8, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [142]:
print(arr[[1, 5]])
print(arr[[1, 5], [2, 3]])


[[ 4  5  6  7]
 [20 21 22 23]]
[ 6 23]


In [148]:
arr[[1, 5]][:, [2, 3]]

array([[ 6,  7],
       [22, 23]])

## 배열 전치

In [151]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [153]:
print(arr.T) # 축이 바뀔 때

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [154]:
arr * 3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42]])

In [160]:
# 행렬의 내적, 곱
print(arr @ arr.T) # 행렬간의 곱
print(np.dot(arr, arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


## numpy 함수

In [166]:
samples = np.random.standard_normal(size = (3, 3))
print(samples) # 3, 3의 배열을 임의로 만들 때 

[[ 0.17893878 -0.52402339  1.49457486]
 [-0.59259319 -1.29515765 -0.45702775]
 [ 1.46462698 -0.72160592 -0.29999229]]


In [170]:
arr1 = np.sqrt(samples) 
# nan : 숫자가 아님, 음수에 루트를 씌었을 때
print(arr1)

[[0.42301157        nan 1.22252806]
 [       nan        nan        nan]
 [1.21021774        nan        nan]]


C:\Users\yerin\AppData\Local\Temp\ipykernel_42424\2910638063.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples)


In [172]:
arr2 = np.abs(samples) # abs = 절댓값 취하기
print(arr2)

[[0.17893878 0.52402339 1.49457486]
 [0.59259319 1.29515765 0.45702775]
 [1.46462698 0.72160592 0.29999229]]


In [174]:
np.isnan(arr1) # 현재 내가 갖고 있는 배열에 nan이 들어있는지 확인

array([[False,  True, False],
       [ True,  True,  True],
       [False,  True,  True]])